/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDisclaimerRouteImport } from './routes/ai-disclaimer'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkspaceRouteImport } from './routes/workspace'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclaimerRoute = AiDisclaimerRouteImport.update({
  id: '/ai-disclaimer',
  path: '/ai-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/copyright': typeof CopyrightRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/copyright': typeof CopyrightRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/copyright': typeof CopyrightRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workspace': typeof WorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ai-disclaimer' | '/copyright' | '/privacy' | '/terms' | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/ai-disclaimer' | '/copyright' | '/privacy' | '/terms' | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/ai-disclaimer'
    | '/copyright'
    | '/privacy'
    | '/terms'
    | '/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDisclaimerRoute: typeof AiDisclaimerRoute
  CopyrightRoute: typeof CopyrightRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclaimer': {
      id: '/ai-disclaimer'
      path: '/ai-disclaimer'
      fullPath: '/ai-disclaimer'
      preLoaderRoute: typeof AiDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDisclaimerRoute: AiDisclaimerRoute,
  CopyrightRoute: CopyrightRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
